behaviors:
  CTFAgentBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1028
      learning_rate: 3.0e-3
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 160
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10e6
    time_horizon: 64
    summary_freq: 10000
